import os
from elasticsearch import Elasticsearch
import json

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = os.environ.get("ELASTIC_PASSWORD")

def create_client():
    # Create the client instance
    client = Elasticsearch(
        "https://localhost:9200",
        ca_certs="certs/http_ca.crt",
        basic_auth=("elastic", ELASTIC_PASSWORD)
    )
    # Successful response!
    print(client.info())
    return client

def save_json_to_els(client, imgIdx):
    jsonFile = f"ocr_res/cropped_{imgIdx}.json"
    if os.path.exists(jsonFile):
        try:
            with open(jsonFile, "r", encoding='utf-8') as f:
                print(imgIdx)
                data = json.load(f)
                detections = data["TextDetections"]
                for det in detections:
                    DetectedText = det["DetectedText"]
                    Polygon = det["ItemPolygon"]
                    advInfo = json.loads(det["AdvancedInfo"])
                    ParagNo = advInfo["Parag"]["ParagNo"] if "Parag" in advInfo else None
                    body={
                        "book": "小学语文三年级下册",
                        "page": imgIdx,
                        "ParagNo": ParagNo,
                        "Polygon": Polygon,
                        "text": DetectedText,
                        "path": f'cropped_{imgIdx}.jpg'
                    }
                    client.index(
                        index = "pep_books",
                        body = body
                    )
        except Exception as e:
            print(e)
